export const ProtectionPlan = [
    {
      "id": "01",
      "name": "Engine Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Engine Oil Service for petrol engines that have been serviced by the use of BG 110 when engine oil and oil filter are changed or diesel engines that have been serviced by the use of BG 112 when engine oil and oil filter are changed. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 4000,
      "planTermId": "1",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "GAS",
      "products": "BG110"
    },
    {
      "id": "02",
      "name": "Engine Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Engine Oil Service for petrol engines that have been serviced by the use of BG 110 when engine oil and oil filter are changed or diesel engines that have been serviced by the use of BG 112 when engine oil and oil filter are changed. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 4000,
      "planTermId": "1",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "DIESEL",
      "products": "BG112"
    },
    {
      "id": "03",
      "name": "Engine Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Engine Oil Service for petrol engines that have been serviced by the use of BG 110 when engine oil and oil filter are changed or diesel engines that have been serviced by the use of BG 112 when engine oil and oil filter are changed. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 2000,
      "planTermId": "2",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "GAS",
      "products": "BG110"
    },
    {
      "id": "04",
      "name": "Engine Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Engine Oil Service for petrol engines that have been serviced by the use of BG 110 when engine oil and oil filter are changed or diesel engines that have been serviced by the use of BG 112 when engine oil and oil filter are changed. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 2000,
      "planTermId": "2",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "DIESEL",
      "products": "BG112"
    },
    {
      "id": "05",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 4000,
      "planTermId": "1",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "GAS",
      "products": "BG110_BG208"
    },
    {
      "id": "06",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 4000,
      "planTermId": "1",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "GAS",
      "products": "BG110_BG213"
    },
    {
      "id": "07",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 4000,
      "planTermId": "1",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "DIESEL",
      "products": "BG112_BG244"
    },
    {
      "id": "08",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 4000,
      "planTermId": "1",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "DIESEL",
      "products": "BG112_BG245"
    },
    {
      "id": "09",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 2000,
      "planTermId": "2",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "GAS",
      "products": "BG110_BG208"
    },
    {
      "id": "10",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 2000,
      "planTermId": "2",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "GAS",
      "products": "BG110_BG213"
    },
    {
      "id": "11",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 2000,
      "planTermId": "2",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "DIESEL",
      "products": "BG112_BG244"
    },
    {
      "id": "12",
      "name": "Premier Oil Service",
      "protectionPlanCategory": "ENGINE_OIL_SERVICES",
      "serviceDescription": "Premier Oil Service for petrol engines and fuel systems that have been serviced by the use of BG 110 and BG 213; or BG 110 and BG 208 when engineo il and oil filter are changed or diesel engines that have been serviced by the use of BG 112 and BG 244 or BG 245 when engine oil and oil filter are changed. BG 407 is optional. Extend the service interval to 10,000 miles/16,000 km when BG 729, BG 737 or OEM approved oil is included.",
      "reimbursementAmount": 2000,
      "planTermId": "2",
      "coverage": "Covers only pistons and rings, wrist pins and bushings, rods and rod bearings, camshafts and bearings, push rods, intake valves and guides (grinding adjustments excluded), turbo bearings, crankshaft and bearings, cylinder liners or bores, valve lifters, timing chains (timing belts and damage to engine parts due to broken timing belts excluded), rocker arms and pivots, oil pump, timing gears or sprockets, distributor drive gear.",
      "serviceInterval": "Service Interval: Coverage will be continued by the performance of the BG Service within 7,500 miles/12,000 km of the previous service (10,000 miles/16,000 km if BG 729, BG 737 or OEM approved oil is used) or 12 months, whichever comes first. From the date of the Protection Plan enrollment, the vehicle’s engine must be serviced only with the proper grade and weight of engine oil, recommended by the vehicle manufacturer. Timing belt and air and oil filter must be replaced and emission control system maintained in accordance with vehicle manufacturer’s recommendations. Effective June 1, 2012.",
      "fuelEngineType": "DIESEL",
      "products": "BG112_BG245"
    },
  ]